services:
  postgres:
    image: postgres:16
    container_name: travel-agency-db
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      TZ: UTC
      PGTZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
