server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD:changeit}
    key-store-type: PKCS12
    key-alias: travelagency
  error:
    include-stacktrace: never
    include-message: never

spring:
  profiles:
    active: prod
  jpa:
    show-sql: false
    properties:
      hibernate:
        auto_quote_keyword: true
    open-in-view: false

  mvc:
    format:
      date: yyyy-MM-dd

  thymeleaf:
    cache: false

app:
  security:
    default-password: "12345678"
    jwt-expiration-ms: 86400000
    blocked-cache-refresh-ms: 30000
    password-min-length: 8
  pagination:
    catalogue-page-size: 9
    manager-page-size: 10
    user-page-size: 10
    admin-page-size: 15
    api-page-size: 20
