# Test profile configuration
spring.profiles.active=test

spring.datasource.url=jdbc:h2:mem:travel_agency_test;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.auto_quote_keyword=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data-test.sql

spring.main.allow-bean-definition-overriding=true

spring.h2.console.enabled=true
